# Generated by Django 5.0.2 on 2024-03-01 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0002_cart_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ant',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
