# Generated by Django 5.0.2 on 2024-03-04 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0003_order_ant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='ant',
            new_name='amt',
        ),
    ]
